### ISSUE TITLE
Bug About Table Insert Function

### ISSUE THREAD

**Issue by Lurvelly** [owensgroup/BGHT#15]
Hi all,

Thanks for sharing your code, it seems very useful.
I want to use your hash table improve my program performance, but when I tested the customer type program "test_types.cu", I found a bug that, the table insert won't return and the GPU-Util will keep 100%.

To reproduce this bug, we need change a little "test_types.cu" code.
https://github.com/owensgroup/BGHT/blob/4e8618ef37ab60021bab5c5a59b5f27257cc58ee/test/test_types.cu#L284-L303

```c++
  std::vector<custom_key> h_keys;
  for(int i =0; i <16; i++)
  {
    h_keys.emplace_back(custom_key{static_cast<size_t>(i),static_cast<uint32_t>(i),static_cast<uint64_t>(i)});
  }

  std::vector<pair_type> h_pairs;
  for(int i = 0; i < 16; i++)
  {
    h_pairs.push_back({h_keys[i], i + 1});
  }

  thrust::device_vector<pair_type> d_pairs(h_pairs);
```
![Screenshot from 2022-12-19 11-09-54](https://user-images.githubusercontent.com/17422260/208413610-6b5489ac-7454-4c56-9957-d64532d9ed3b.png)

I also attacted the the code to reproduce this bug, you can have a try.
[test_types.zip](https://github.com/owensgroup/BGHT/files/10258789/test_types.zip)

My cuda version below:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

If you would like to kown any other information, please feel free contact me. 

Best Regards
---------------
Louis Li

**Comment by maawad** [comment]
Hi @Lurvelly, 

Thanks for reporting the bug and the very well-documented bug report. I was able to reproduce the bug. The problem is that your code is trying to insert the sentinel key-value pair (see, [`invalid_key`](https://github.com/owensgroup/BGHT/blob/4e8618ef37ab60021bab5c5a59b5f27257cc58ee/test/test_types.cu#L278) and the [constructor](https://github.com/owensgroup/BGHT/blob/4e8618ef37ab60021bab5c5a59b5f27257cc58ee/test/test_types.cu#L281)) into the hash table. 

In this case, I believe insertion should just fail. All insertion functions return `true` on success, and now if you try to insert a pair where the key is the sentinel key, insertion will fail and returns false. I added the required code and a unit test in this [commit](https://github.com/owensgroup/BGHT/commit/f5e196068ba13621a6a637be5127d4621196952d) and merged it to the main.

Please let me know if you have questions! Thanks.

**Comment by Lurvelly** [comment]
Hi @maawad 

Thanks your prompt reply.  I have tested your commit, it seems working properly. 


Just for my curious. You said that the previous problem is that I am trying to insert the sentinel key-value pair into the hash table. But I found that if I change a little in my test code, the problem will will disappear ( also try to insert the sentinel key-value pair into the hash table). So I would like to know if there is another bug exist.

## Case 1:  Insert value with the same index ( don't add 1 )
```c++
  std::vector<custom_key> h_keys;
  for(int i =0; i <16; i++)
  {
    h_keys.emplace_back(custom_key{static_cast<size_t>(i),static_cast<uint32_t>(i),static_cast<uint64_t>(i)});
  }

  std::vector<pair_type> h_pairs;
  for(int i = 0; i < 16; i++)
  {
    //h_pairs.push_back({h_keys[i], i + 1});
    h_pairs.push_back({h_keys[i], i});
  }

  thrust::device_vector<pair_type> d_pairs(h_pairs);

```

## Case 2:  Recude the key-value quantity from 16 to 8.
```c++
  std::vector<custom_key> h_keys;
  for(int i =0; i < 8; i++)
  {
    h_keys.emplace_back(custom_key{static_cast<size_t>(i),static_cast<uint32_t>(i),static_cast<uint64_t>(i)});
  }

  std::vector<pair_type> h_pairs;
  for(int i = 0; i < 8; i++)
  {
    h_pairs.push_back({h_keys[i], i + 1});
  }

  thrust::device_vector<pair_type> d_pairs(h_pairs);

```

> These code works with insertion functions return `true` on success. ([Nov 11, 2022 Version](https://github.com/owensgroup/BGHT/tree/4e8618ef37ab60021bab5c5a59b5f27257cc58ee))

Thanks aging for your work.

Best Regards
---------------
Louis Li

**Comment by Lurvelly** [comment]
Change status to open

**Comment by maawad** [comment]
Hi @Lurvelly, Thanks for testing the commit! 

Let me give you a more detailed explanation to satisfy your curiosity.  

In the implementation, we assume that the user will never insert the sentinel key, so then when we compute the load, we ignore any sentinel key:

https://github.com/owensgroup/BGHT/blob/b80c606ca13b7df5dca67b09d9ad95241a7c245d/include/detail/bucket.cuh#L37-L41
 
 Now, if you insert `{sentinel_key, random_value},` that insertion will succeed, but then the implementation gets stuck in an infinite loop (the bug you found). The compute load function sees the location where you inserted the sentinel key as empty, but the compare-and-swap operation internally compares both the key and value simultaneously to the sentinel key-value pair and fails. The compare and swap only succeed if it successfully replaces `{sentinel_key, sentinel_value}` with `{key, value}.`
 
 If you insert  `{sentinel_key, sentinel_value},` that insertion will succeed, and the following insertion will overwrite it because the compare-and-swap will succeed (no infinite loop -- case 1). 
 
For case 2, in this specific example, it happens that the 9th key collides with the 1st key, and that is where the infinite loop happens. If you increase the load factor (i.e., decrease the [128 capacity](https://github.com/owensgroup/BGHT/blob/main/test/test_types.cu#L281)), you will see the same bug. 


After writing this explanation, I noticed that a different (better) solution is to compare both key and value to the sentinel pair when computing the load, and then the only pair that the user should never insert is  `{sentinel_key, sentinel_value}`  which is way less restrictive than ` {sentinel_key,any_key}.`  This solution requires more changes to the code.

Hope this answers your questions! Please feel free to ask more questions or open issues if you find any bugs!

**Comment by Lurvelly** [comment]
Hi @maawad , 

Thanks for your detailed explanation,  you have made that crystal clear.

In my view, normally we will not insert `{sentinel_key, sentinel_value}` into hash tables. I insert the `{sentinel_key, sentinel_value}` into hash table purely by accident. Usually, I wanna use a `key` and `value` that my data won't reach as the `sentinel_key` and `sentinel_value`, then the case that user insert `{sentinel_key, sentinel_value}` into hash tables will disappear. So I think you would better try the new solution if the new (better) solution have better performance. There is no need to worry about whether user will insert `{sentinel_key, sentinel_value}` or not.  

Looking forword to your new code.

> I will close this issue. And If I found other bugs, I will let you know asap.

Best Regards
-------------------
Louis Li
